// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTB_BOOTH4WALLACE_MULTIPLIER_NBIT__SYMS_H_
#define VERILATED_VTB_BOOTH4WALLACE_MULTIPLIER_NBIT__SYMS_H_  // guard

#include "verilated.h"
#include "verilated_vcd_c.h"

// INCLUDE MODEL CLASS

#include "Vtb_booth4wallace_multiplier_nbit.h"

// INCLUDE MODULE CLASSES
#include "Vtb_booth4wallace_multiplier_nbit___024root.h"
#include "Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit.h"

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vtb_booth4wallace_multiplier_nbit__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtb_booth4wallace_multiplier_nbit* const __Vm_modelp;
    bool __Vm_dumping = false;  // Dumping is active
    VerilatedMutex __Vm_dumperMutex;  // Protect __Vm_dumperp
    VerilatedVcdC* __Vm_dumperp VL_GUARDED_BY(__Vm_dumperMutex) = nullptr;  /// Trace class for $dump*
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtb_booth4wallace_multiplier_nbit___024root TOP;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__10__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__13__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__16__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__1__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__4__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__7__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__10__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__1__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__4__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__7__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__0__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__3__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__6__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__0__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__3__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__1__KET____DOT__u_op_3_to_2_nbit;
    Vtb_booth4wallace_multiplier_nbit_op_3_to_2_nbit TOP__tb_booth4wallace_multiplier_nbit__DOT__dut__DOT__u_op_n_to_2_nbit__DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__u_op_n_to_2_nbit_onestage__DOT__genblk1__BRA__0__KET____DOT__u_op_3_to_2_nbit;

    // CONSTRUCTORS
    Vtb_booth4wallace_multiplier_nbit__Syms(VerilatedContext* contextp, const char* namep, Vtb_booth4wallace_multiplier_nbit* modelp);
    ~Vtb_booth4wallace_multiplier_nbit__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
    void _traceDump();
    void _traceDumpOpen();
    void _traceDumpClose();
};

#endif  // guard
